function createfigure2(xdata1, ydata1, zdata1, zdata2)
%CREATEFIGURE2(xdata1, ydata1, zdata1, zdata2)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata
%  ZDATA2:  surface zdata

%  Auto-generated by MATLAB on 25-Aug-2023 15:05:32

% Create figure
figure1 = figure('InvertHardcopy','off','Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.110357142857143 0.088888882833814 0.777022066460479 0.367579368106903]);
hold(axes1,'on');

% Create surf
surf(xdata1,ydata1,zdata1,'Parent',axes1);

% Create zlabel
zlabel({''});

% Create ylabel
ylabel({'PD2'},'FontName','Times New Roman');

% Create xlabel
xlabel({'PD1'},'FontName','Times New Roman');

% Create title
title({'NN-OptNet'},'FontSize',11);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[20 65]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[50 210.777390754663]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[7689.09942093889 15908.7616317145]);
view(axes1,[0.434814940643456 90]);
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman');
% Create colorbar
colorbar(axes1,'Position',...
    [0.909404762703035 0.105555549500481 0.028571428571429 0.805158736213805]);

% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.110357142857143 0.550119047619048 0.775 0.3725]);
hold(axes2,'on');

% Create surf
surf(xdata1,ydata1,zdata2,'Parent',axes2);

% Create ylabel
ylabel({'PD2'},'FontName','Times New Roman');

% Create title
title({'Optimizer'},'FontWeight','bold','FontSize',11,...
    'FontName','Times New Roman');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[20 65]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[50 210.777390754663]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes2,[7371.92944286575 15655.6429015617]);
view(axes2,[-0.2081480244522 90]);
grid(axes2,'on');
hold(axes2,'off');
% Set the remaining axes properties
set(axes2,'FontName','Times New Roman');
